### ISSUE TITLE
No plugin exists with the handle "scss"

### ISSUE THREAD

**Issue by epartipilo** [chasegiunta/craft-scss#3]
I just installed the last version on Craft and I cannot activate the plugin.

Thanks in advanced for any information.

**Comment by chasegiunta** [comment]
@epartipilo hard to say but I haven't had a single bug report for this plugin in quite a while. I was just able to install on my own instance locally - it might be something weird going on in your environment?

**Comment by epartipilo** [comment]
Hi, @chasegiunta 
Well I just roll back one Craft3 version and rebuild the project.
Is working fine now.
Thanks!!
