### ISSUE TITLE
Craft 4 support?

### ISSUE THREAD

**Issue by TommasoSangiorgio** [chasegiunta/craft-scss#5]

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3), as people are keen to see this plugin on Craft 4.

If you're no longer developing this plugin, we'd be happy to continue development at Verbb (including updating to Craft 4) - but just let us know if you've got plans to continue things and update to Craft 4! @chasegiunta

**Comment by chasegiunta** [comment]
@TommasoSangiorgio Not sure when it will be visible on the plugin store, but I've just released a cut for Craft 4. Thanks for the heads up and willingness to help @engram-design !!

**Comment by engram-design** [comment]
Nice one @chasegiunta I'll take it off the list!
